# Generated by Django 4.2.2 on 2023-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email Address')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
